stages:
    - build

variables:
  MOVIE_URL: "https://$MYDOWNLOADSERVER/sample.avi"

.fedora: &fc
    stage: build
    before_script:
    - dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
    - dnf -y install curl make gcc-c++ ffmpeg-devel gd-devel zlib-devel libpng-devel
    - curl --output /home/sample.avi -L $MOVIE_URL
    script:
    - cd src
    - make test
    - mv /tmp/*.jpg ..
    artifacts:
        name: mtn-$CI_JOB_NAME
        expire_in: 4 week
        paths:
        - ./bin/*
        - ./*.jpg

.centOS: &el
    stage: build
    rules:
    - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "devel"
      when: manual
    before_script:
    - yum -y install https://download1.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %centos).noarch.rpm
    - yum -y install curl make gcc-c++ ffmpeg-devel gd-devel zlib-devel libpng-devel
    - curl --output /home/sample.avi -L $MOVIE_URL
    script:
    - cd src
    - make test
    - mv /tmp/*.jpg ..
    artifacts:
        name: mtn-$CI_JOB_NAME
        expire_in: 4 week
        paths:
        - ./bin/*
        - ./*.jpg

.ubu: &ubuntu
    stage: build
    rules:
    - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "devel"
      when: manual
    before_script:
    - apt-get -y update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install curl gcc make libgd-dev libavutil-dev libavcodec-dev libavformat-dev libswscale-dev
    - curl --output /home/sample.avi -L $MOVIE_URL
    script:
    - cd src
    - make test
    - mv /tmp/*.jpg ..
    artifacts:
        name: mtn-$CI_JOB_NAME
        expire_in: 4 week
        paths:
        - ./*.jpg

debian:
    image: debian:9
    stage: build
    variables:
        STATIC_GD_BRANCH: GD-2.2
        STATIC_FFMPEG_BRANCH: release/4.0
    rules:
    - if: $CI_PROJECT_NAMESPACE == "movie_thumbnailer"
      when: manual
    before_script:
    - sh misc/gitlab-ci-info.sh > build_info.txt
    - apt update
    - apt install -y git wget libc6-dev zlib1g-dev libpng-dev libbz2-dev libjpeg-dev libfreetype6-dev pkg-config gcc make g++ cmake
    - wget --no-verbose --no-clobber -O /home/sample.avi $MOVIE_URL || echo $MOVIE_URL exists
    script:
    - echo cloning FFmpeg branch $STATIC_FFMPEG_BRANCH...
    - git clone --depth=1 -b $STATIC_FFMPEG_BRANCH https://github.com/FFmpeg/FFmpeg.git lib/FFmpeg
    - echo cloning GD branch $STATIC_GD_BRANCH...
    - git clone --depth=1 -b $STATIC_GD_BRANCH https://github.com/libgd/libgd.git lib/libgd
    - patch -p1 < misc/gdjpeg.patch
    - cd lib/FFmpeg
    - sh -e ../../misc/configureFFmpeg.sh
    - make -j4
    - cd -
    - cd lib/libgd
    - cmake -DBUILD_SHARED_LIBS=0 -DBUILD_STATIC_LIBS=1 -DENABLE_FREETYPE=1 -DENABLE_JPEG=1 -DENABLE_PNG=1 -DFREETYPE_INCLUDE_DIR_ft2build=/usr/include/freetype2 -DFREETYPE_INCLUDE_DIR_freetype2=/usr/include/freetype2 .
    - make -j4
    - cd -
    - cd src
    - make tests
    - cd -
    - pushd lib/FFmpeg
    - make distclean
    - popd
    - pushd lib/libgd
    - make distclean
    - popd
    - tar czhf mtn-static.tar.gz *
    - mv /tmp/*.jpg .
    artifacts:
        name: mtn-$CI_JOB_NAME
        expire_in: 4 week
        paths:
        - ./bin/mtn
        - ./mtn-static.tar.gz
        - ./*.jpg

win:
    image: fedora:31
    stage: build
    variables:
        WIN_FFMPEG_VER: 3.4.2
    rules:
    - if: $CI_PROJECT_NAMESPACE == "movie_thumbnailer"
      when: manual
    before_script:
    - sh misc/gitlab-ci-info.sh > build_info.txt
    - dnf -y install curl unzip make mingw32-gcc.x86_64
    # MYDOWNLOADSERVER = ffmpeg.zeranoe.com/builds/win32/...
    - curl --output /tmp/deps-win-libgd.tgz      -L https://$MYDOWNLOADSERVER/deps-libgd-2.1.1-x86.tgz
    - curl --output /tmp/ffmpeg-win32-dev.zip    -L https://$MYDOWNLOADSERVER/ffmpeg-$WIN_FFMPEG_VER-win32-dev.zip
    - curl --output /tmp/ffmpeg-win32-shared.zip -L https://$MYDOWNLOADSERVER/ffmpeg-$WIN_FFMPEG_VER-win32-shared.zip

    script:
    - mkdir -p lib
    - unzip -d lib /tmp/ffmpeg-win32-dev.zip
    - mv lib/ffmpeg-*-dev lib/windows
    - mkdir -p lib/windows/bin
    - unzip -j -d lib/windows/bin /tmp/ffmpeg-win32-shared.zip ffmpeg-*-win32-shared/bin/{avcodec*.dll,avformat*.dll,avutil*.dll,sw*.dll}
    - tar xzf /tmp/deps-win-libgd.tgz -C lib/windows
    - cd src
    - make -f Makefile.mingw
    - cd ..
    - mkdir -p mtn-win32/bin
    - mv lib/windows/bin/* mtn-win32/bin/
    - mv bin/mtn.exe mtn-win32/bin/
    - cp -r src mtn-win32/
    - cp ./*.txt mtn-win32/
    - cp ./*.md mtn-win32/
    artifacts:
        name: mtn-$CI_JOB_NAME
        expire_in: 4 week
        paths:
        - mtn-win32

# new RPM
fc_latest:
    image: fedora:latest
    <<: *fc

# old RPM
centos7:
    image: centos:7
    <<: *el

# new DEB
ubuntu_devel:
    image: ubuntu:devel
    <<: *ubuntu

# old DEB
u18.04:
    image: ubuntu:18.04
    <<: *ubuntu
