clone:
    depth: 1

pipelines:
  branches:
    master:
        - step:
            image: wahibre/mtn-build
            #trigger: manual
            script:
#   shared build
              - pushd src
              - make test
              - popd
              - tar czf mtn-latest.tgz bin/mtn
              - curl -X POST --user "${CI_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"mtn-latest.tgz"
#   static build
#              - mv /home/mtn-a/ lib
#              - pushd src
#              - make tests
#              - popd
#              - tar czhf mtn-latest-static.tgz bin/mtn lib/FFmpeg lib/libgd lib/libpng.a lib/libz.a
#              - curl -X POST --user "${CI_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"mtn-latest-static.tgz"
