clone:
    depth: 1

pipelines:
  custom:
    ubuntu:
      - step:  
          image: wahibre/mtn:u17.10
          script:
          - pushd src
          - make test
          - popd
          - mkdir -p builddeb/DEBS/usr/bin builddeb/DEBS/usr/share/doc/mtn
          - mv bin/mtn builddeb/DEBS/usr/bin/
          - mv doc README* *gpl*.txt builddeb/DEBS/usr/share/doc/mtn/
          - cd builddeb
          - chmod -R 755 rootdirectory
          - dpkg-deb --build rootdirectory DEBS
          - cd DEBS
          - DEB_FILE=`ls mtn*.deb`
          - curl -X POST --user "${CI_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${DEB_FILE}"

    f26mixed:
      - step:
           image: wahibre/mtn:f26
           #trigger: manual
           script:
#   rpm build
              - tar cf mtn.tar *
              - mkdir -p buildroot/SOURCES
              - mv mtn.tar buildroot/SOURCES/
              - rpmbuild -bb --define "_topdir $(pwd)/buildroot" buildrpm/mtn.spec
#   static build
              - mv /home/mtn-a/ lib
              - pushd lib
              - tar xzf /home/mingw32.tgz
              - tar xzf /home/mtn-deps.tgz
              - popd
              - pushd src
              #build linux static binary
              - make tests
              #build windows shared binary
              - make -f Makefile.mingw
              - popd
              - tar czhf mtn-latest-static.tgz bin/mtn lib/FFmpeg lib/libgd lib/libpng.a lib/libz.a
              - mv bin/mtn.exe lib/mingw32/bin/
              - mv lib/mingw32/bin lib/mingw32/mtn-latest
              - pushd lib/mingw32
              - zip -r mtn-latest-win32.zip mtn-latest
              - popd
              - curl -X POST --user "${CI_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"mtn-latest-static.tgz"
              - curl -X POST --user "${CI_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"lib/mingw32/mtn-latest-win32.zip"
              - curl -X POST --user "${CI_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"`ls buildroot/RPMS/x86_64/*.rpm`"
    fedora27:
      - step:
           image: wahibre/mtn:f27
           script:
                - tar cf mtn.tar *
                - mkdir -p buildroot/SOURCES
                - mv mtn.tar buildroot/SOURCES/
                - rpmbuild -bb --define "_topdir $(pwd)/buildroot" buildrpm/mtn.spec
                - curl -X POST --user "${CI_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"`ls buildroot/RPMS/x86_64/*.rpm`"
